#!/usr/bin/env python

"""codelock.py:  Helper utility that encrypts a directory requested by the
user.It assumes a pre compiled picrypt binary is located at /usr/bin/picrypt"""

from __future__ import print_function
import os
import re
import sys
import time
from subprocess import call, Popen, PIPE
import argparse

__author__ = "Minos Galanakis"
__license__ = "GPL v3"
__version__ = "0.0.1"
__email__ = "minos197@gmail.com"
__project__ = "PiCrypt"
__date__ = "01-07-2016"

# Templates for stat-up methods
rcloc_tpl = (r"\\\nsleep 5\necho \$(/usr/bin/picrypt --ramkey) | "
             r"ecryptfs-add-passphrase --fnek > /dev/null\n"
             r"/bin/mount -t ecryptfs %(mdir)s  %(mdir)s >/dev/null\n"
             r"sleep 5 && rm -f /tmp/lock.key\n")

sysd_tpl = ("[Unit]\n"
            "Description=PiCrypt Key Creator\n"
            "DefaultDependencies=no\n"
            "After=sysinit.target\n\n"
            "[Install]\n"
            "WantedBy=multi-user.target\n\n"
            "[Service]\n"
            "TimeoutStartSec=0\n"
            "Type=oneshot\n"
            "ExecStart=/bin/sh -c '/bin/echo $(/usr/bin/picrypt --ramkey) |"
            " /usr/bin/ecryptfs-add-passphrase --fnek > /dev/null'\n"
            "ExecStart=/bin/sh -c 'mount -t ecryptfs  %(mdir)s  %(mdir)s'\n"
            "ExecStart=/bin/sh -c '/bin/sleep 5 && rm -r /tmp/lock.key'")

systemd_svc_file = "/lib/systemd/system/picrypt.service"

def run(cmd):
    p = Popen(cmd, shell=True, stdout=PIPE, stderr=PIPE)
    ret, err = p.communicate()
    if not p.returncode:
        return ret.strip()
    else:
        raise RuntimeError(err)

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--dir",
                        "-d",
                        help="Select the directory that will be locked",
                        dest="target",
                        action="store")
    parser.add_argument("--systemd",
                        "-s",
                        help="Add hooks to systemd instead of rc.local",
                        dest="systemd",
                        default=False,
                        action="store_true")

    usr_args = parser.parse_args()
    # Verify the unlock program exists.
    if not os.path.isfile("/usr/bin/picrypt"):
        print("Make sure picrypt is located at /usr/bin/picrypt")
        sys.exit(1)

    # If the argument is not there
    if not usr_args.target:
        print("Target directory not specified")
        print("\tUsage: codelock /opt/yourdir")
        sys.exit(1)
    else:
        # Convert to absolute path
        target = os.path.abspath(usr_args.target)
        if not os.path.isdir(target):
            print("Directory %s does not exist." % target)
            sys.exit(1)

    # If dirctory is not empty
    if os.listdir(target):
        print("Copying files to temporary directory")
        print("WARNING!. This is a RAM limited operation and will fail\n if"
              "size of data in %s is greater than memory." % target)
        time.sleep(3)

        # Make a working directory
        run("mkdir -p /tmp/codelock")

        # Copy existing data there
        run("cp -prf %s/* /tmp/codelock/" % target)

    elif not call("mkdir -p %s" % target, shell=True):
        print("Created new directory %s" % target)
    else:
        print("%s is not a valid target directory" % target)
        sys.exit(1)

    try:
        # Get the hardware related password
        passwd = run("picrypt --hash")
        print("password:    ", passwd)

        # Add it to keyring
        r = run(('printf "%s" "passphrase" | ecryptfs-add-passphrase'
                ' --fnek') % passwd)

        # Fetch hashes from keyring
        sig, fnek_sig = re.findall(r'(?:\[)(.*)(?:\])', r)
        if not sig or not fnek_sig:
            print("Error adding to keychain")
            sys.exit(1)
        print("signature:   ", sig)
        print("fnek_sig:    ", fnek_sig)

        # Mount the encrypted directory
        options = ["verbose=yes",
                   "key=passphrase:passphrase_passwd=%s" % passwd,
                   "ecryptfs_fnek_sig=%s" % fnek_sig,
                   "ecryptfs_enable_filename_crypto=y",
                   "ecryptfs_sig=%s" % sig,
                   "no_sig_cache=y",
                   "ecryptfs_cipher=aes",
                   "ecryptfs_key_bytes=16",
                   "ecryptfs_passthrough=n"]
        mnt_cmd = "mount -t ecryptfs -o %s %s %s" % (",".join(options),
                                                     target,
                                                     target)
        print(mnt_cmd)
        run(mnt_cmd)
        print("Mounted directory with encryption")

        # If intermediate directory exists copy data over
        if os.path.isdir("/tmp/codelock/"):
            print("Copying files to encrypted directory")
            run("cp -prf /tmp/codelock/* %s" % (target))

        # create the automount file
        mnt_rc = ["key=passphrase:passphrase_passwd_file=/tmp/lock.key",
                  "ecryptfs_unlink_sigs",
                  "ecryptfs_sig=%s" % sig,
                  "ecryptfs_fnek_sig=%s" % fnek_sig,
                  "ecryptfs_cipher=aes",
                  "ecryptfs_key_bytes=16",
                  "no_sig_cache=y",
                  "ecryptfs_passthrough=n",
                  "ecryptfs_enable_filename_crypto=y"]
        with open("/root/.ecryptfsrc", "w") as F:
            F.write("\n".join(mnt_rc))
        print("Created /root/.ecryptfsrc")

        run("mkdir -p /root/.ecryptfs/")
        with open("/root/.ecryptfs/sig-cache.txt", "w") as F:
            F.write(sig+"\n")
        print("Created /root/.ecryptfs/sig-cache.txt")

    # Add the entry to fstab
    if not usr_args.systemd:
        rclocal = rcloc_tpl % {"mdir": target}
        cmd = r'sed -i "/fi/a\%s" /etc/rc.local' % rclocal
        run(cmd)
        print("Added rc.local boot entry")
    else:
        systemd = sysd_tpl % {"mdir": target}
        with open(systemd_svc_file, "w") as F:
            F.write(sysd_tpl % {"mdir": target})
        cmd = r'systemctl daemon-reload && systemctl enable picrypt'
        run(cmd)
        print("Added Systemd boot entry")

        # Cleanup
        run("rm -rf /tmp/codelock")
        print("Done Please reboot the system to test")
    except Exception as e:
        print("Failed", e.message)
